apiVersion: apps/v1
kind: Deployment
metadata:
  name: so-model-depl
  labels:
    app: so-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: so-model
  template:
    metadata:
      labels:
        app: so-model
    spec:
      containers:
      - name: so-model
        image: ghcr.io/remla22-group3/stackoverflow-tag-detection:0.0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: so-model-svc
spec:
  selector:
    app: so-model
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: so-web-depl
  labels:
    app: so-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: so-web
  template:
    metadata:
      labels:
        app: so-web
    spec:
      containers:
      - name: so-web
        image: ghcr.io/remla22-group3/stackoverflow-web-app:0.0.1
        ports:
        - containerPort: 8080
        env:
          - name: MODEL_HOST
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: model.host
---
apiVersion: v1
kind: Service
metadata:
  name: so-web-svc
  labels:
    app: so-web-svc
spec:
  selector:
    app: so-web
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-monitor
  labels:
    release: promstack
spec:
  selector:
    matchLabels:
      app: so-web-svc
  endpoints:
  - targetPort: 8080
    path: "/metrics"
    interval: 1s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  defaultBackend:
    service:
      name: so-web-svc
      port:
        number: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  model.host: "http://so-model-svc:8080"